# docker-compose.yml
version: '3.8'

services:
  api:
    build: .
    container_name: fastapi_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
    restart: unless-stopped